### ISSUE TITLE
implement "GetSingleProject" action 

### ISSUE THREAD

**Issue by Manuelrincon37** [dev-isaak/time-keeper#14]
Create action "GetSingleProject"  on projectStorage.js to:

1. get current proeject data
2. display data (name) when crono is running

**Comment by dev-isaak** [comment]
This option is already available. The function getDailyHours obtain all the projects data.
Check this line:

```
        if (this.dailyHoursList[0].data.is_started === true) {
          this.isStarted = true
          this.lastDocId = this.dailyHoursList[0].id
          this.lastTimeStart = this.dailyHoursList[0].data.starting_time_ms
          this.lastTimeStartFormatted = this.dailyHoursList[0].data.starting_time
        }
```

If is_started means that is the current project. Then you can get all the info from there, or add new data.
