### ISSUE TITLE
[BUG] Total Weekly hours and Total monthly hours are Showing NaN

### ISSUE THREAD

**Issue by Manuelrincon37** [dev-isaak/time-keeper#17]
### Current Behavior:
 When enter in statistics view the circles displaying the hours show NaN. 

### Expected Behavior:
The circles must display values in numbres as 00:00 h

### Steps To Reproduce:

1. log ing
2. Go to statistics
3. The circles will show NaN

### Environment:

- OS: Ubuntu 20.04
- Node: 13.14.0
- npm: 7.6.3

**Comment by Manuelrincon37** [comment]
![image](https://github.com/dev-isaak/time-keeper/assets/133518631/e016f80c-44f0-4245-89f7-3b2ea898ba92)

**For some reason in HoursArray if the data in my user, one of de items is "0-1:57 h" thats causing the function getWeeklyHours and getMonthlyHours trhow NaN**

PS: maybe modifing the code in the future to ensure that all the intems in hoursArray are in fatc numbers

**Comment by dev-isaak** [comment]
This is caused because in the DB are recorded all the timing with an old format that we are not using any more. Now the format that we are sending to totalMonthlyHours and totalWeeklyHours will be "hh:mm".
I'm going to delete all the data recorded so far, and let's check if this is happening again.
